# 项目相关配置
server:
  port: 10001
  tomcat:
    uri-encoding: UTF-8
    max-threads: 800
    min-spare-threads: 30



# Spring配置
spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: druid,redis
  devtools:
    restart:
      enabled: true
  mvc:
    static-path-pattern: /**
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/

  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false



  datasource:
    db1:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/prinectsignaldaata?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: root
      password: root
      hikari:
        maximum-pool-size: 50

    db2:
      driver-class-name:  com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/prinectjobdata?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: root
      password: root
      hikari:
        maximum-pool-size: 50

    db3:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/prinectsignaldaata_copy?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: root
      password: root
      hikari:
        maximum-pool-size: 50

    db4:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/prinectjobdata_copy?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: root
      password: root
      hikari:
        maximum-pool-size: 50


hdb:
  #远端服务器域名
  domainName: http://192.168.1.215:15011
  #远端服务器地址
  serverUrl: http://192.168.1.215:15011/PrinectAPILocal/rest/device/action/subscription
  #sqlite job数据库地址
  sqliteDBJobUrl: D:/sqlite/db1/hdb_job.db
  #sqlite other数据库地址
  sqliteDBOtherUrl: D:/sqlite/db2/hdb_other.db
  #sqlite数据备份地址
  backupDBUrl: D:/sqlite/DBbackup
  #数据源服务器接口身份认证
  authorization: Basic U3Bhcms6c3Bhcms=
  #加解密盐  注意*此盐目前不生效，先写死在加解密类里
  salt: hdbsaltabcdefg
  isOpenLog: true
  notLogFilerPath: /index,/js/



mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*/*.xml



  #logging:
  #file:
  #name: D:/hdb/hdb.log
